version: "3.9"

services:
  build: ./api
  ports:
    - 3000:3000
  depends_on:
    - db
  volumes:
    - ./api/src:/usr/app/src
  environment:
    - PG_CONNECTION_STRING: postgres://${POSTGRES_USER}

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    enviromnent:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - 

  
  
